version: "3"
services:
  db:
    environment:
      - POSTGRES_PASSWORD=emeis
  emeis:
    build:
      context: .
      args:
        REQUIREMENTS: requirements-dev.txt
    user: "${UID:?Set UID env variable to your user id}"
    volumes:
      - ./:/app
    command:
      [
        "/bin/sh",
        "-c",
        "wait-for-it db:5432 -- ./manage.py migrate && ./manage.py runserver_plus --keep-meta-shutdown --nostatic 0.0.0.0:8000",
      ]
    environment:
      - ENV=dev
      - ALLOW_ANONYMOUS_WRITE=true
