# Generated by Django 2.2.13 on 2020-06-11 05:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_acl_permission_role_scope_make_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="acl",
            name="meta",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, verbose_name="meta"
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="meta",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, verbose_name="meta"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="meta",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, verbose_name="meta"
            ),
        ),
        migrations.AddField(
            model_name="scope",
            name="meta",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, verbose_name="meta"
            ),
        ),
    ]
