# Generated by Django 3.2.25 on 2024-06-03 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emeis_core", "0010_scope_full_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scope",
            options={"ordering": ["full_name"]},
        ),
        migrations.RemoveField(
            model_name="scope",
            name="level",
        ),
        migrations.RemoveField(
            model_name="scope",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="scope",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="scope",
            name="tree_id",
        ),
        migrations.AlterField(
            model_name="scope",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="emeis_core.scope",
                verbose_name="parent",
            ),
        ),
    ]
